# Generated by Django 5.1.1 on 2024-09-18 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_address', models.TextField()),
                ('working_schedule', models.TextField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='dentalApp.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('specialties', models.CharField(choices=[('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening'), ('filling', 'Filling'), ('root canal', 'Root Canal'), ('crown', 'Crown')], default='cleaning', max_length=50)),
                ('clinics', models.ManyToManyField(through='dentalApp.Affiliation', to='dentalApp.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='affiliation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='dentalApp.doctor'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('ssn_no', models.CharField(max_length=4)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='female', max_length=50)),
                ('last_visit_procedure', models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening'), ('filling', 'Filling'), ('root canal', 'Root Canal'), ('crown', 'Crown')], max_length=100, null=True)),
                ('next_visit', models.DateTimeField(blank=True)),
                ('next_visit_procedure', models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening'), ('filling', 'Filling'), ('root canal', 'Root Canal'), ('crown', 'Crown')], max_length=100, null=True)),
                ('last_visit_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_doctor', to='dentalApp.doctor')),
                ('next_visit_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_doctor', to='dentalApp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(choices=[('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening'), ('filling', 'Filling'), ('root canal', 'Root Canal'), ('crown', 'Crown')], default='cleaning', max_length=50)),
                ('date', models.DateTimeField()),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalApp.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalApp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dentalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedures_done', models.CharField(choices=[('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening'), ('filling', 'Filling'), ('root canal', 'Root Canal'), ('crown', 'Crown')], default='cleaning', max_length=50)),
                ('doctor_notes', models.TextField()),
                ('date', models.DateTimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalApp.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalApp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='dentalApp.patient')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('doctor', 'clinic')},
        ),
    ]
