# Generated by Django 5.1.1 on 2024-09-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='last_visit_doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_visit_doctor',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.CharField(choices=[('filling', 'Filling'), ('root canal', 'Root Canal'), ('crown', 'Crown'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening')], default='cleaning', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.CharField(choices=[('filling', 'Filling'), ('root canal', 'Root Canal'), ('crown', 'Crown'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening')], default='cleaning', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='female', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_visit_procedure',
            field=models.CharField(blank=True, choices=[('filling', 'Filling'), ('root canal', 'Root Canal'), ('crown', 'Crown'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_visit_procedure',
            field=models.CharField(blank=True, choices=[('filling', 'Filling'), ('root canal', 'Root Canal'), ('crown', 'Crown'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='procedures_done',
            field=models.CharField(choices=[('filling', 'Filling'), ('root canal', 'Root Canal'), ('crown', 'Crown'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening')], default='cleaning', max_length=50),
        ),
    ]
