# Generated by Django 5.1.1 on 2024-09-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalApp', '0002_remove_patient_last_visit_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.CharField(choices=[('filling', 'Filling'), ('teeth whitening', 'Teeth Whitening'), ('cleaning', 'Cleaning'), ('crown', 'Crown'), ('root canal', 'Root Canal')], default='cleaning', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.CharField(choices=[('filling', 'Filling'), ('teeth whitening', 'Teeth Whitening'), ('cleaning', 'Cleaning'), ('crown', 'Crown'), ('root canal', 'Root Canal')], default='cleaning', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_visit_procedure',
            field=models.CharField(blank=True, choices=[('filling', 'Filling'), ('teeth whitening', 'Teeth Whitening'), ('cleaning', 'Cleaning'), ('crown', 'Crown'), ('root canal', 'Root Canal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_visit_procedure',
            field=models.CharField(blank=True, choices=[('filling', 'Filling'), ('teeth whitening', 'Teeth Whitening'), ('cleaning', 'Cleaning'), ('crown', 'Crown'), ('root canal', 'Root Canal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='procedures_done',
            field=models.CharField(choices=[('filling', 'Filling'), ('teeth whitening', 'Teeth Whitening'), ('cleaning', 'Cleaning'), ('crown', 'Crown'), ('root canal', 'Root Canal')], default='cleaning', max_length=50),
        ),
    ]
