# Generated by Django 5.1.1 on 2024-09-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalApp', '0003_alter_appointment_procedure_alter_doctor_specialties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.CharField(choices=[('filling', 'Filling'), ('root canal', 'Root Canal'), ('cleaning', 'Cleaning'), ('crown', 'Crown'), ('teeth whitening', 'Teeth Whitening')], default='cleaning', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.CharField(choices=[('filling', 'Filling'), ('root canal', 'Root Canal'), ('cleaning', 'Cleaning'), ('crown', 'Crown'), ('teeth whitening', 'Teeth Whitening')], default='cleaning', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('other', 'Other'), ('male', 'Male'), ('female', 'Female')], default='female', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_visit_procedure',
            field=models.CharField(blank=True, choices=[('filling', 'Filling'), ('root canal', 'Root Canal'), ('cleaning', 'Cleaning'), ('crown', 'Crown'), ('teeth whitening', 'Teeth Whitening')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_visit_procedure',
            field=models.CharField(blank=True, choices=[('filling', 'Filling'), ('root canal', 'Root Canal'), ('cleaning', 'Cleaning'), ('crown', 'Crown'), ('teeth whitening', 'Teeth Whitening')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='procedures_done',
            field=models.CharField(choices=[('filling', 'Filling'), ('root canal', 'Root Canal'), ('cleaning', 'Cleaning'), ('crown', 'Crown'), ('teeth whitening', 'Teeth Whitening')], default='cleaning', max_length=50),
        ),
    ]
