# Generated by Django 5.1.1 on 2024-09-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalApp', '0008_remove_patient_next_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.CharField(choices=[('root canal', 'Root Canal'), ('filling', 'Filling'), ('crown', 'Crown'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening')], default='cleaning', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.CharField(choices=[('root canal', 'Root Canal'), ('filling', 'Filling'), ('crown', 'Crown'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening')], default='cleaning', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('other', 'Other'), ('female', 'Female')], default='female', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_visit_procedure',
            field=models.CharField(blank=True, choices=[('root canal', 'Root Canal'), ('filling', 'Filling'), ('crown', 'Crown'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_visit_procedure',
            field=models.CharField(blank=True, choices=[('root canal', 'Root Canal'), ('filling', 'Filling'), ('crown', 'Crown'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='procedures_done',
            field=models.CharField(choices=[('root canal', 'Root Canal'), ('filling', 'Filling'), ('crown', 'Crown'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening')], default='cleaning', max_length=50),
        ),
    ]
