# Generated by Django 5.1.1 on 2024-09-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalApp', '0009_alter_appointment_procedure_alter_doctor_specialties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.CharField(choices=[('root canal', 'Root Canal'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening'), ('filling', 'Filling'), ('crown', 'Crown')], default='cleaning', max_length=50),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.CharField(choices=[('root canal', 'Root Canal'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening'), ('filling', 'Filling'), ('crown', 'Crown')], default='cleaning', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='female', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_visit_procedure',
            field=models.CharField(blank=True, choices=[('root canal', 'Root Canal'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening'), ('filling', 'Filling'), ('crown', 'Crown')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_visit_procedure',
            field=models.CharField(blank=True, choices=[('root canal', 'Root Canal'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening'), ('filling', 'Filling'), ('crown', 'Crown')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ssn_no',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='procedures_done',
            field=models.CharField(choices=[('root canal', 'Root Canal'), ('cleaning', 'Cleaning'), ('teeth whitening', 'Teeth Whitening'), ('filling', 'Filling'), ('crown', 'Crown')], default='cleaning', max_length=50),
        ),
    ]
